# This file was auto-generated by cabal2nix. Please do NOT edit manually!

{ cabal, baseUnicodeSymbols, colour, diagramsCairo, diagramsCore
, diagramsGtk, diagramsLib, glib, gtk, JuicyPixels, mtl, split, stm
, stmChans, transformers
}:

cabal.mkDerivation (self: {
  pname = "mosaico-lib";
  version = "0.1.0.0";
  src = ./.;
  buildDepends = [
    baseUnicodeSymbols colour diagramsCairo diagramsCore diagramsGtk
    diagramsLib glib gtk JuicyPixels mtl split stm stmChans
    transformers
  ];
  meta = {
    homepage = "http://ldc.usb.ve/~05-38235/cursos/CI3661/2015AJ/";
    description = "Generación interactiva de mosaicos";
    license = self.stdenv.lib.licenses.bsd3;
    platforms = self.ghc.meta.platforms;
  };
  enableSplitObjs = false;
})
